export * from './company.service';
import { CompanyService } from './company.service';
export * from './configuration.service';
import { ConfigurationService } from './configuration.service';
export * from './editTimeSpan.service';
import { EditTimeSpanService } from './editTimeSpan.service';
export * from './health.service';
import { HealthService } from './health.service';
export * from './loginDomain.service';
import { LoginDomainService } from './loginDomain.service';
export * from './mark.service';
import { MarkService } from './mark.service';
export * from './oidcConfiguration.service';
import { OidcConfigurationService } from './oidcConfiguration.service';
export * from './profession.service';
import { ProfessionService } from './profession.service';
export * from './professionArea.service';
import { ProfessionAreaService } from './professionArea.service';
export * from './rating.service';
import { RatingService } from './rating.service';
export * from './ratingCategory.service';
import { RatingCategoryService } from './ratingCategory.service';
export * from './schoolClass.service';
import { SchoolClassService } from './schoolClass.service';
export * from './semester.service';
import { SemesterService } from './semester.service';
export * from './semesterRating.service';
import { SemesterRatingService } from './semesterRating.service';
export * from './student.service';
import { StudentService } from './student.service';
export * from './subject.service';
import { SubjectService } from './subject.service';
export * from './teacher.service';
import { TeacherService } from './teacher.service';
export * from './userConfiguration.service';
import { UserConfigurationService } from './userConfiguration.service';
export const APIS = [CompanyService, ConfigurationService, EditTimeSpanService, HealthService, LoginDomainService, MarkService, OidcConfigurationService, ProfessionService, ProfessionAreaService, RatingService, RatingCategoryService, SchoolClassService, SemesterService, SemesterRatingService, StudentService, SubjectService, TeacherService, UserConfigurationService];
