/**
 * GBS_MyPerformance
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProfessionAreaDTO } from './professionAreaDTO';
import { RoundingTypeDTO } from './roundingTypeDTO';
import { SemesterDTO } from './semesterDTO';
import { StudentDTO } from './studentDTO';

export interface ProfessionDTO { 
    id?: string;
    name?: string;
    diplomaRoundingType?: RoundingTypeDTO;
    professionAreaId?: string;
    professionArea?: ProfessionAreaDTO;
    activeFrom?: Date;
    activeTo?: Date;
    students?: Array<StudentDTO>;
    semesters?: Array<SemesterDTO>;
    readonly isActive?: boolean;
}