/**
 * GBS_MyPerformance
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MarkDTO } from './markDTO';
import { RatingCategoryDTO } from './ratingCategoryDTO';
import { SubjectDTO } from './subjectDTO';

export interface RatingDTO { 
    id?: string;
    subjectId?: string;
    subject?: SubjectDTO;
    ratingCategoryId?: string;
    ratingCategory?: RatingCategoryDTO;
    marks?: Array<MarkDTO>;
}