/**
 * GBS_MyPerformance
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type RoundingTypeDTO = 1 | 5;

export const RoundingTypeDTO = {
    NUMBER_1: 1 as RoundingTypeDTO,
    NUMBER_5: 5 as RoundingTypeDTO
};