/**
 * GBS_MyPerformance
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProfessionAreaDTO } from './professionAreaDTO';
import { StudentDTO } from './studentDTO';
import { TeacherDTO } from './teacherDTO';

export interface SchoolClassDTO { 
    id?: string;
    name?: string;
    starting?: Date;
    ending?: Date;
    einschreibeschluesselCode?: string;
    einschreibeSchluessel?: string;
    students?: Array<StudentDTO>;
    teacherId?: string;
    teacher?: TeacherDTO;
    professionAreaId?: string;
    professionArea?: ProfessionAreaDTO;
}