/**
 * GBS_MyPerformance
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProfessionDTO } from './professionDTO';
import { SemesterRatingDTO } from './semesterRatingDTO';

export interface SemesterDTO { 
    id?: string;
    number?: number;
    semesterRatings?: Array<SemesterRatingDTO>;
    professionId?: string;
    profession?: ProfessionDTO;
}