/**
 * GBS_MyPerformance
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApprenticeTrainerDTO } from './apprenticeTrainerDTO';
import { CompanyDTO } from './companyDTO';
import { MarkDTO } from './markDTO';
import { ProfessionDTO } from './professionDTO';
import { SchoolClassDTO } from './schoolClassDTO';
import { UserRolesDTO } from './userRolesDTO';

export interface StudentDTO { 
    id?: string;
    userName?: string;
    normalizedUserName?: string;
    email?: string;
    normalizedEmail?: string;
    emailConfirmed?: boolean;
    passwordHash?: string;
    securityStamp?: string;
    concurrencyStamp?: string;
    phoneNumber?: string;
    phoneNumberConfirmed?: boolean;
    twoFactorEnabled?: boolean;
    lockoutEnd?: Date;
    lockoutEnabled?: boolean;
    accessFailedCount?: number;
    firstName?: string;
    lastName?: string;
    passwordInitialSetPending?: boolean;
    mainRole?: UserRolesDTO;
    readonly name?: string;
    apprenticeTrainerEmail?: string;
    apprenticeTrainerId?: string;
    apprenticeTrainer?: ApprenticeTrainerDTO;
    professionId?: string;
    profession?: ProfessionDTO;
    companyId?: string;
    company?: CompanyDTO;
    schoolClassId?: string;
    schoolClass?: SchoolClassDTO;
    marks?: Array<MarkDTO>;
}