/**
 * GBS_MyPerformance
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProfessionAreaDTO } from './professionAreaDTO';
import { RatingDTO } from './ratingDTO';
import { RoundingTypeDTO } from './roundingTypeDTO';

export interface SubjectDTO { 
    id?: string;
    abbreviation?: string;
    name?: string;
    remarks?: string;
    markRoundingType?: RoundingTypeDTO;
    ratings?: Array<RatingDTO>;
    professionAreaId?: string;
    professionArea?: ProfessionAreaDTO;
}