name: Docker / unstable
on:
  push:
    branches:
      - develop
      - feature/gh-actions
concurrency: gbs_myperformance
jobs:
  docker-unstable:
    name: docker
    runs-on: [self-hosted, windows]
    uses: ./.github/workflows/docker.yml
      with:
        APP_TAG: unstable
      secrets:
        DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
        DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        DOCKER_REGISTRY_TOKEN: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

# name: Docker Build unstable
# on:
#   push:
#     branches:
#       - develop
# env:
#   APP_TAG: unstable
# concurrency: gbs_myperformance
# ---

# name: Docker Build Version
